# The current version of the config schema
version: 1
# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". If blank, will refer to environment. Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    review-open-prs: search prs --repo "$1" --state=open --limit=10 --draft=false --checks=success --json createdAt,commentsCount,title,url --jq '.[].createdAt |= sub("T.+Z"; "") | sort_by(.createdAt, .commentsCount) | .[0:9][] | "\(.title)\n\(.url)\n"'
    review-open-involved-prs: search prs --repo "$1" --involves=@me --state=open --json title,url --jq '.[] | "\(.title)\n\(.url)\n"'
    review-my-open-prs: search prs --author=@me --state=open --json title,url --jq '.[] | "\(.title)\n\(.url)\n"'
    raise-pr: pr create --draft --title "$1" --template "$2" --reviewer "$3"
# The path to a unix socket through which send HTTP connections. If blank, HTTP traffic will be handled by net/http.DefaultTransport.
http_unix_socket:
# What web browser gh should use when opening URLs. If blank, will refer to environment.
browser:
